List vc
khrystyna-sb/Countries pull request #4
Opened 2021-11-26 16:56 UTC by khrystyna-sb

2021-11-26 18:14 UTC, apolwork requested changes
- Check scale for your flag assets. You could set it to vector and it would not require 2x and 3x files
- Cleanup API files. You have two of them

2021-11-26 18:14 UTC, apolwork commented on Countries/API.swift
> +
Do you have file duplication?

2021-11-26 18:14 UTC, apolwork commented on Countries/DetailsViewController.swift
> +
Do we need this enum?

2021-11-26 18:14 UTC, apolwork commented on Countries/ListViewController.swift
> +
Please, clean up such changes

2021-11-26 18:14 UTC, apolwork commented on Countries/ListViewController.swift
> +
saa

2021-11-26 18:14 UTC, apolwork commented on Countries/ListViewController.swift
> +
saa

2021-11-26 18:14 UTC, apolwork commented on Countries/ListViewController.swift
> +                       imageName: imageName)
You could pass `Country` object here

2021-11-26 18:14 UTC, apolwork commented on Countries/ListViewController.swift
> +
saa

2021-11-26 18:14 UTC, apolwork commented on Countries/CountryTableViewCell.swift
> +        // how to not copie paste the same code?
Lazy var could help you

2021-11-26 18:14 UTC, apolwork commented on Countries/CountryTableViewCell.swift
> +        stackView.addArrangedSubview(regionLabel)
Don't update view hierarchy in layout subviews. 
E.g. move this code to stackview property

2021-11-26 18:14 UTC, apolwork commented on Countries/CountryTableViewCell.swift
> +        let stackHeightSize = contentView.frame.height
You could use Layout constraints instead of manual layout.

2021-11-26 18:14 UTC, apolwork commented on Countries/CountryTableViewCell.swift
> +        flagImageView.frame = CGRect(x: 1, y: 1, width: imageSideSize, height: imageSideSize )
saa

2021-11-29 10:30 UTC, khrystyna-sb commented on Countries/ListViewController.swift
> +                       imageName: imageName)
brilliant idea

2021-11-29 13:35 UTC, khrystyna-sb commented on Countries/CountryTableViewCell.swift
> +        let stackHeightSize = contentView.frame.height
could you tell me which method should I use for it? I mean like ViewDidLoad in VC, where should I put my NSLayoutConstraint.activate([])

2021-11-29 13:41 UTC, khrystyna-sb commented on Countries/CountryTableViewCell.swift
> +        stackView.addArrangedSubview(regionLabel)
it yelling on me like this "Instance member 'nameLabel' cannot be used on type 'CountryTableViewCell'; did you mean to use a value of this type instead?" when I move this code to stackview property

2021-11-29 13:50 UTC, khrystyna-sb commented on Countries/CountryTableViewCell.swift
> +        let stackHeightSize = contentView.frame.height
used init

2021-11-29 14:04 UTC, apolwork commented on Countries/CountryTableViewCell.swift
> +        stackView.addArrangedSubview(regionLabel)
```
class View: UIView {
    lazy var label1: UILabel = {
        let view = UILabel()
        view.text = "Label 1"
        return view
    }()

    lazy var stack: UIStackView = {
        let view = UIStackView()

        return view
    }()

    override init(frame: CGRect) {
        super.init(frame: frame)

        stack.addArrangedSubview(label1)
        stack.frame = CGRect(x: 0, y: 0, width: 200, height: 200)
        addSubview(stack)
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}```

Try something similar with your codes.

2021-11-29 14:08 UTC, apolwork commented on Countries/CountryTableViewCell.swift
> +        let stackHeightSize = contentView.frame.height
The best place to place it is to place in place where you create your view related to this constraint.

Also init could be good place to set contraints

2021-11-29 14:13 UTC, apolwork reviewed
Good progress continue in the same way

2021-11-29 14:13 UTC, apolwork commented on Countries/CountryTableViewCell.swift
> +    }
👍

2021-11-29 14:15 UTC, khrystyna-sb commented on Countries/CountryTableViewCell.swift
> +        stackView.addArrangedSubview(regionLabel)
thank you

2021-11-29 14:40 UTC, khrystyna-sb commented on Countries/API.swift
> +
fixed

2021-11-29 17:21 UTC, apolwork requested changes

2021-11-29 17:21 UTC, apolwork commented on Countries/DetailsViewController.swift
> +            stackView.addArrangedSubview(label)
If your country does not have capital, it would not present any data.

2021-11-29 17:39 UTC, apolwork approved these changes

2021-11-30 12:08 UTC, merged